name: bhhh_noise
description: bhhh noise is simple relaxing music player with mixing your favorite noises

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.30
  just_audio_windows: any
  just_audio_mpv: any
  flutter_bloc: ^8.1.1
  url_launcher: ^6.1.6
  flutter_animate: ^2.0.1
  firebase_core: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
