// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRnFLkAxcc5QPHq2hUBKa-3j_LsXAOqh8',
    appId: '1:982630579115:web:0da25561a408f7c6dfb0ee',
    messagingSenderId: '982630579115',
    projectId: 'bhhh-noise',
    authDomain: 'bhhh-noise.firebaseapp.com',
    storageBucket: 'bhhh-noise.appspot.com',
    measurementId: 'G-J87005ZXKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGvO3PgKz33t_BAeKDp78CXNDZUMG4MaI',
    appId: '1:982630579115:android:b4e11763f7e40127dfb0ee',
    messagingSenderId: '982630579115',
    projectId: 'bhhh-noise',
    storageBucket: 'bhhh-noise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-tYpjY0ThOmjVXAxudbsdlavD-L8Wak',
    appId: '1:982630579115:ios:0bb8812c59731bf4dfb0ee',
    messagingSenderId: '982630579115',
    projectId: 'bhhh-noise',
    storageBucket: 'bhhh-noise.appspot.com',
    iosClientId: '982630579115-ta616o8319bv9cai6nu6dc6l5jfjoof8.apps.googleusercontent.com',
    iosBundleId: 'com.example.shhhNoise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ-tYpjY0ThOmjVXAxudbsdlavD-L8Wak',
    appId: '1:982630579115:ios:0bb8812c59731bf4dfb0ee',
    messagingSenderId: '982630579115',
    projectId: 'bhhh-noise',
    storageBucket: 'bhhh-noise.appspot.com',
    iosClientId: '982630579115-ta616o8319bv9cai6nu6dc6l5jfjoof8.apps.googleusercontent.com',
    iosBundleId: 'com.example.shhhNoise',
  );
}
